# version: '3.8'

services:
  edinception3d-claude:
    image: edinception3d-claude:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3007
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.edinception3d-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.edinception3d-http.entrypoints=http
      - traefik.http.routers.edinception3d-http.middlewares=https-redirect
      - traefik.http.routers.edinception3d-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.edinception3d-https.entrypoints=https
      - traefik.http.routers.edinception3d-https.tls=true
      - traefik.http.routers.edinception3d-https.tls.certresolver=le
      - traefik.http.routers.edinception3d-https.service=edinception3d-service
      - traefik.http.services.edinception3d-service.loadbalancer.server.port=3007
    networks:
      # - web
      - traefik-public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/api/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  # web:
  #   external: true
  traefik-public:
    external: true